server:
  port: 5051
db:
  name: customerdb
spring:
  h2:
    console:
      enabled: true
hibernate:
  defaultSchema: customer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/