server:
  port: 5052
spring:
  profiles:
    active: development
  application:
    name: item-Service
  h2:
    console:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'