server:
  port: 5052
db:
  name: itemdb
spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
       hibernate:
          default_schema: customer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'